trigger:
  - master

jobs:
  - job: ci
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: .azure-pipelines/install-node-modules.yml
      - script: yarn nx run-many --target=lint --all
      - script: yarn nx run-many --target=test --all
      - script: yarn nx run-many --target=build --all --prod